// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using suivi_des_drones.Core.Infrastructure.Databases;

#nullable disable

namespace suivi_des_drones.Core.Infrastructure.Migrations
{
    [DbContext(typeof(DronesDbContext))]
    partial class DronesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("suivi_des_drones.Core.Models.CompleteUser", b =>
                {
                    b.Property<string>("Login")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Login");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("suivi_des_drones.Core.Models.Drone", b =>
                {
                    b.Property<string>("Matricule")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("HealthStatusId")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Matricule");

                    b.HasIndex("HealthStatusId");

                    b.ToTable("Drone", (string)null);
                });

            modelBuilder.Entity("suivi_des_drones.Core.Models.HealthStatus", b =>
                {
                    b.Property<decimal>("Id")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HealthStatus", (string)null);
                });

            modelBuilder.Entity("suivi_des_drones.Core.Models.Drone", b =>
                {
                    b.HasOne("suivi_des_drones.Core.Models.HealthStatus", "HealthStatus")
                        .WithMany("Drones")
                        .HasForeignKey("HealthStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HealthStatus");
                });

            modelBuilder.Entity("suivi_des_drones.Core.Models.HealthStatus", b =>
                {
                    b.Navigation("Drones");
                });
#pragma warning restore 612, 618
        }
    }
}
